window.GH_COLORS = {
    "Others": "#ccc",
    "ABAP": "#ccc",
    "AGS Script": "#B9D9FF",
    "ANTLR": "#9DC3FF",
    "APL": "#8a0707",
    "ASP": "#6a40fd",
    "ATS": "#1ac620",
    "ActionScript": "#e3491a",
    "Ada": "#02f88c",
    "Agda": "#467C91",
    "Alloy": "#cc5c24",
    "Ant Build System": "#ccc",
    "ApacheConf": "#ccc",
    "Apex": "#ccc",
    "AppleScript": "#ccc",
    "Arc": "#ca2afe",
    "Arduino": "#bd79d1",
    "AsciiDoc": "#ccc",
    "AspectJ": "#1957b0",
    "Assembly": "#a67219",
    "Augeas": "#ccc",
    "AutoHotkey": "#6594b9",
    "AutoIt": "#36699B",
    "Awk": "#ccc",
    "Batchfile": "#ccc",
    "Befunge": "#ccc",
    "Bison": "#ccc",
    "BitBake": "#ccc",
    "BlitzBasic": "#ccc",
    "BlitzMax": "#cd6400",
    "Bluespec": "#ccc",
    "Boo": "#d4bec1",
    "Brainfuck": "#ccc",
    "Brightscript": "#ccc",
    "Bro": "#ccc",
    "C": "#555",
    "C#": "#178600",
    "C++": "#f34b7d",
    "C-ObjDump": "#ccc",
    "C2hs Haskell": "#ccc",
    "CLIPS": "#ccc",
    "CMake": "#ccc",
    "COBOL": "#ccc",
    "CSS": "#563d7c",
    "Cap'n Proto": "#ccc",
    "CartoCSS": "#ccc",
    "Ceylon": "#ccc",
    "Chapel": "#8dc63f",
    "ChucK": "#ccc",
    "Cirru": "#aaaaff",
    "Clean": "#3a81ad",
    "Clojure": "#db5855",
    "CoffeeScript": "#244776",
    "ColdFusion": "#ed2cd6",
    "ColdFusion CFC": "#ed2cd6",
    "Common Lisp": "#3fb68b",
    "Component Pascal": "#b0ce4e",
    "Cool": "#ccc",
    "Coq": "#ccc",
    "Cpp-ObjDump": "#ccc",
    "Creole": "#ccc",
    "Crystal": "#ccc",
    "Cucumber": "#ccc",
    "Cuda": "#ccc",
    "Cycript": "#ccc",
    "Cython": "#ccc",
    "D": "#fcd46d",
    "D-ObjDump": "#ccc",
    "DM": "#075ff1",
    "Darcs Patch": "#ccc",
    "Dart": "#98BAD6",
    "Diff": "#ccc",
    "Dockerfile": "#ccc",
    "Dogescript": "#cca760",
    "Dylan": "#3ebc27",
    "E": "#ccce35",
    "ECL": "#8a1267",
    "Eagle": "#3994bc",
    "Ecere Projects": "#ccc",
    "Eiffel": "#946d57",
    "Elixir": "#6e4a7e",
    "Elm": "#60B5CC",
    "Emacs Lisp": "#c065db",
    "EmberScript": "#f64e3e",
    "Erlang": "#0faf8d",
    "F#": "#b845fc",
    "FLUX": "#33CCFF",
    "FORTRAN": "#4d41b1",
    "Factor": "#636746",
    "Fancy": "#7b9db4",
    "Fantom": "#dbded5",
    "Forth": "#341708",
    "Frege": "#00cafe",
    "G-code": "#ccc",
    "GAMS": "#ccc",
    "GAP": "#ccc",
    "GAS": "#ccc",
    "GDScript": "#ccc",
    "GLSL": "#ccc",
    "Game Maker Language": "#8ad353",
    "Genshi": "#ccc",
    "Gentoo Ebuild": "#ccc",
    "Gentoo Eclass": "#ccc",
    "Gettext Catalog": "#ccc",
    "Glyph": "#e4cc98",
    "Gnuplot": "#f0a9f0",
    "Go": "#375eab",
    "Golo": "#f6a51f",
    "Gosu": "#82937f",
    "Grace": "#ccc",
    "Gradle": "#ccc",
    "Grammatical Framework": "#ff0000",
    "Graph Modeling Language": "#ccc",
    "Graphviz (DOT)": "#ccc",
    "Groff": "#ccc",
    "Groovy": "#e69f56",
    "Groovy Server Pages": "#ccc",
    "HTML": "#ccc",
    "HTML+Django": "#ccc",
    "HTML+ERB": "#ccc",
    "HTML+PHP": "#ccc",
    "HTTP": "#ccc",
    "Hack": "#ccc",
    "Haml": "#ccc",
    "Handlebars": "#ccc",
    "Harbour": "#0e60e3",
    "Haskell": "#29b544",
    "Haxe": "#f7941e",
    "Hy": "#7891b1",
    "IDL": "#e3592c",
    "IGOR Pro": "#ccc",
    "INI": "#ccc",
    "IRC log": "#ccc",
    "Idris": "#ccc",
    "Inform 7": "#ccc",
    "Inno Setup": "#ccc",
    "Io": "#a9188d",
    "Ioke": "#078193",
    "Isabelle": "#fdcd00",
    "J": "#ccc",
    "JSON": "#ccc",
    "JSON5": "#ccc",
    "JSONLD": "#ccc",
    "JSONiq": "#ccc",
    "Jade": "#ccc",
    "Jasmin": "#ccc",
    "Java": "#b07219",
    "Java Server Pages": "#ccc",
    "JavaScript": "#f1e05a",
    "Julia": "#a270ba",
    "KRL": "#f5c800",
    "Kit": "#ccc",
    "Kotlin": "#ccc",
    "LFE": "#004200",
    "LLVM": "#ccc",
    "LOLCODE": "#cc9900",
    "LSL": "#3d9970",
    "LabVIEW": "#ccc",
    "Lasso": "#2584c3",
    "Latte": "#A8FF97",
    "Less": "#ccc",
    "LilyPond": "#ccc",
    "Liquid": "#ccc",
    "Literate Agda": "#ccc",
    "Literate CoffeeScript": "#ccc",
    "Literate Haskell": "#ccc",
    "LiveScript": "#499886",
    "Logos": "#ccc",
    "Logtalk": "#ccc",
    "LookML": "#652B81",
    "LoomScript": "#ccc",
    "Lua": "#fa1fa1",
    "M": "#ccc",
    "MTML": "#0095d9",
    "Makefile": "#ccc",
    "Mako": "#ccc",
    "Markdown": "#ccc",
    "Mask": "#f97732",
    "Mathematica": "#ccc",
    "Matlab": "#bb92ac",
    "Maven POM": "#ccc",
    "Max": "#ce279c",
    "MediaWiki": "#ccc",
    "Mercury": "#abcdef",
    "MiniD": "#ccc",
    "Mirah": "#c7a938",
    "Monkey": "#ccc",
    "Moocode": "#ccc",
    "MoonScript": "#ccc",
    "Myghty": "#ccc",
    "NSIS": "#ccc",
    "Nemerle": "#0d3c6e",
    "NetLogo": "#ff2b2b",
    "Nginx": "#ccc",
    "Nimrod": "#37775b",
    "Ninja": "#ccc",
    "Nit": "#0d8921",
    "Nix": "#7070ff",
    "Nu": "#c9df40",
    "NumPy": "#ccc",
    "OCaml": "#3be133",
    "ObjDump": "#ccc",
    "Objective-C": "#438eff",
    "Objective-C++": "#4886FC",
    "Objective-J": "#ff0c5a",
    "Omgrofl": "#cabbff",
    "Opa": "#ccc",
    "Opal": "#f7ede0",
    "OpenCL": "#ccc",
    "OpenEdge ABL": "#ccc",
    "OpenSCAD": "#ccc",
    "Org": "#ccc",
    "Ox": "#ccc",
    "Oxygene": "#5a63a3",
    "Oz": "#fcaf3e",
    "PAWN": "#dbb284",
    "PHP": "#4F5D95",
    "Pan": "#cc0000",
    "Papyrus": "#6600cc",
    "Parrot": "#f3ca0a",
    "Parrot Assembly": "#ccc",
    "Parrot Internal Representation": "#ccc",
    "Pascal": "#b0ce4e",
    "Perl": "#0298c3",
    "Perl6": "#0298c3",
    "PigLatin": "#fcd7de",
    "Pike": "#066ab2",
    "Pod": "#ccc",
    "PogoScript": "#d80074",
    "PostScript": "#ccc",
    "PowerShell": "#ccc",
    "Processing": "#2779ab",
    "Prolog": "#74283c",
    "Propeller Spin": "#2b446d",
    "Protocol Buffer": "#ccc",
    "Public Key": "#ccc",
    "Puppet": "#cc5555",
    "Pure Data": "#91de79",
    "PureBasic": "#5a6986",
    "PureScript": "#bcdc53",
    "Python": "#3581ba",
    "Python traceback": "#ccc",
    "QML": "#44a51c",
    "QMake": "#ccc",
    "R": "#198ce7",
    "RAML": "#77d9fb",
    "RDoc": "#ccc",
    "REALbasic": "#ccc",
    "RHTML": "#ccc",
    "RMarkdown": "#ccc",
    "Racket": "#ae17ff",
    "Ragel in Ruby Host": "#ff9c2e",
    "Raw token data": "#ccc",
    "Rebol": "#358a5b",
    "Red": "#ee0000",
    "Redcode": "#ccc",
    "RobotFramework": "#ccc",
    "Rouge": "#cc0088",
    "Ruby": "#701516",
    "Rust": "#dea584",
    "SAS": "#1E90FF",
    "SCSS": "#ccc",
    "SPARQL": "#ccc",
    "SQF": "#FFCB1F",
    "SQL": "#ccc",
    "STON": "#ccc",
    "Sage": "#ccc",
    "SaltStack": "#ccc",
    "Sass": "#ccc",
    "Scala": "#7dd3b0",
    "Scaml": "#ccc",
    "Scheme": "#1e4aec",
    "Scilab": "#ccc",
    "Self": "#0579aa",
    "Shell": "#89e051",
    "ShellSession": "#ccc",
    "Shen": "#120F14",
    "Slash": "#007eff",
    "Slim": "#ff8877",
    "Smalltalk": "#596706",
    "Smarty": "#ccc",
    "SourcePawn": "#f69e1d",
    "Squirrel": "#ccc",
    "Standard ML": "#dc566d",
    "Stata": "#ccc",
    "Stylus": "#ccc",
    "SuperCollider": "#46390b",
    "Swift": "#ffac45",
    "SystemVerilog": "#343761",
    "TOML": "#ccc",
    "TXL": "#ccc",
    "Tcl": "#e4cc98",
    "Tcsh": "#ccc",
    "TeX": "#3D6117",
    "Tea": "#ccc",
    "Text": "#ccc",
    "Textile": "#ccc",
    "Thrift": "#ccc",
    "Turing": "#45f715",
    "Turtle": "#ccc",
    "Twig": "#ccc",
    "TypeScript": "#31859c",
    "Unified Parallel C": "#755223",
    "UnrealScript": "#a54c4d",
    "VCL": "#0298c3",
    "VHDL": "#543978",
    "Vala": "#ee7d06",
    "Verilog": "#848bf3",
    "VimL": "#199c4b",
    "Visual Basic": "#945db7",
    "Volt": "#0098db",
    "Web Ontology Language": "#3994bc",
    "WebIDL": "#ccc",
    "XC": "#ccc",
    "XML": "#ccc",
    "XProc": "#ccc",
    "XQuery": "#2700e2",
    "XS": "#ccc",
    "XSLT": "#ccc",
    "Xojo": "#ccc",
    "Xtend": "#ccc",
    "YAML": "#ccc",
    "Zephir": "#118f9e",
    "Zimpl": "#ccc",
    "eC": "#ccc",
    "edn": "#db5855",
    "fish": "#ccc",
    "mupad": "#ccc",
    "nesC": "#ffce3b",
    "ooc": "#b0b77e",
    "reStructuredText": "#ccc",
    "wisp": "#7582D1",
    "xBase": "#3a4040"
};
